"""
report.py — assemble the one-page Markdown report from pipeline results.

build_markdown_report(results) -> str
"""

from __future__ import annotations

import pandas as pd


def _fmt(x, nd=3):
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return "—"
    if isinstance(x, float):
        return f"{x:,.{nd}f}"
    return str(x)


def build_markdown_report(results: dict) -> str:
    s = results["summary"]
    labels = results["labels"]
    old_l, new_l = labels["old"], labels["new"]

    pct = s["pct_delta"]
    direction = "up" if (pct or 0) >= 0 else "down"
    arrow = "▲" if (pct or 0) >= 0 else "▼"

    lines = []
    lines.append("# Emission-Factor Version Explainer — Report")
    lines.append("")
    lines.append(
        f"**Comparing DEFRA {old_l} → {new_l}.** "
        "Carbon (kg CO₂e) only. Figures reflect the product's bill-of-materials "
        "recomputed under each factor version."
    )
    lines.append("")

    # Headline
    lines.append("## Headline")
    lines.append("")
    lines.append(
        f"Footprint moved from **{_fmt(s['total_old'])} → {_fmt(s['total_new'])} "
        f"kg CO₂e** ({arrow} {_fmt(abs(pct) if pct is not None else None,2)}% {direction})."
    )
    lines.append("")
    lines.append(
        f"- Coverage: **{s['coverage_pct']}%** of the bill-of-materials could be "
        f"computed ({s['lines_included']}/{s['lines_total']} lines). "
        f"{s['lines_excluded']} line(s) excluded — see *Needs review* below."
    )
    if results["context"].get("breaches_baseline"):
        lines.append(
            "- ⚠️ **Target flag:** the footprint increased, which would **breach a "
            "flat baseline** — flag for review against active targets (e.g. SBTi)."
        )
    else:
        lines.append("- ✅ Footprint did not increase against a flat baseline.")

    ds = results.get("diff_stats")
    if ds:
        lines.append(
            f"- Version scan: **{ds['flagged']}** factors moved past DEFRA's "
            f"materiality thresholds across {ds['joined']} factors present in both "
            f"years; {ds['added']} added and {ds['removed']} removed "
            f"(added/removed include DEFRA relabels and are not counted as movers)."
        )
    lines.append("")

    # Biggest movers in the footprint
    lines.append("## Biggest contributors to the change")
    lines.append("")
    top = results["top_delta"]
    if top is None or top.empty:
        lines.append("_No computable movers._")
    else:
        lines.append("| Line item | Factor (old → new) | kg CO₂e (old → new) | Δ |")
        lines.append("|---|---|---|---|")
        for _, r in top.iterrows():
            lines.append(
                f"| {r['line_item']} | {_fmt(r['factor_old'])} → {_fmt(r['factor_new'])} "
                f"| {_fmt(r['co2e_old'])} → {_fmt(r['co2e_new'])} | {_fmt(r['line_delta'])} |"
            )
    lines.append("")

    # Explanations (the moat)
    lines.append("## What changed and why (grounded in the DEFRA changes notes)")
    lines.append("")
    if not results["explanations"]:
        lines.append("_No flagged, footprint-relevant factor changes._")
    for e in results["explanations"]:
        lines.append(
            f"### {e['activity']}  ·  {e['scope']}  ·  "
            f"{_fmt(e['kg_co2e_old'])} → {_fmt(e['kg_co2e_new'])} "
            f"({_fmt(e['pct_change'],1)}%)"
        )
        lines.append("")
        lines.append(f"**Why it changed.** {e['plain_english_reason']}")
        lines.append("")
        lines.append(f"**Methodology note.** {e['methodology_note']}")
        lines.append("")
        lines.append(f"**Target impact.** {e['target_impact_flag']}")
        lines.append("")

    # Needs review
    lines.append("## Needs review (not auto-matched — never guessed)")
    lines.append("")
    mc = results["match_coverage"]
    lines.append(
        f"{mc['auto_matched']}/{mc['total_lines']} lines matched automatically "
        f"({mc['auto_match_pct']}%). The following were left for a human:"
    )
    lines.append("")
    review = results["matched_df"][results["matched_df"]["needs_review"]]
    if review.empty:
        lines.append("_None — every line matched with confidence._")
    else:
        lines.append("| Line item | Unit | Best score | Reason |")
        lines.append("|---|---|---|---|")
        for _, r in review.iterrows():
            lines.append(
                f"| {r['line_item']} | {r['unit']} | {_fmt(r['match_score'],1)} "
                f"| below confidence threshold |"
            )
    lines.append("")
    lines.append("---")
    lines.append(
        "_Generated by EF Version Explainer. Explanations are grounded strictly in "
        "the official DEFRA changes report; where the report is silent, the tool "
        "says so rather than inventing a reason._"
    )
    lines.append("")
    return "\n".join(lines)
